name: weather_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  geolocator: ^12.0.0
  weather: ^3.1.1
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  get_it: ^7.6.7
  get: ^4.6.6
  http: ^1.2.1
  google_maps_flutter: ^2.6.1
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  google_fonts: ^6.2.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.13
  multi_image_picker_view: ^0.0.15
  image_cropper: ^5.0.1
  image_picker: ^1.1.0
  animated_bottom_navigation_bar: ^1.3.3
  flutter_svg: ^2.0.5
  dotted_border: ^2.0.0+3
  geocoding: ^2.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  flutter_local_notifications: ^17.2.1+2
  workmanager: ^0.5.2
  flutter_timezone: ^2.1.0
  onesignal_flutter: ^5.2.2
  firebase_core: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

